#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT_GUESS = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT_GUESS / "student"))

import train_student_5s_hardlabel_baseline as v1  # noqa: E402


def find_default_audio(repo: Path) -> Path:
    preferred = repo / "Dataset" / "fsc22" / "23birdchirping"
    if preferred.is_dir():
        files = sorted([
            p for p in preferred.iterdir()
            if p.suffix.lower() in {".wav", ".flac", ".mp3", ".ogg"}
        ])
        if files:
            return files[0]

    root = repo / "Dataset" / "fsc22"
    for p in sorted(root.rglob("*")):
        if p.suffix.lower() in {".wav", ".flac", ".mp3", ".ogg"}:
            return p

    raise FileNotFoundError("Could not find a default audio file under Dataset/fsc22")


def format_int8_array(values: np.ndarray, values_per_line: int = 16) -> str:
    flat = values.reshape(-1)
    lines = []
    for i in range(0, len(flat), values_per_line):
        chunk = flat[i:i + values_per_line]
        lines.append("  " + ", ".join(str(int(x)) for x in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    parser.add_argument("--audio", default=None)
    parser.add_argument("--out-dir", default="firmware/preprocess/testdata")
    args = parser.parse_args()

    repo = Path(args.repo_root).resolve()
    audio = Path(args.audio).resolve() if args.audio else find_default_audio(repo)
    out_dir = repo / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    normalizer_path = repo / "student" / "final_models" / "5s_kd_hw08_kw02" / "normalizer.json"
    export_summary_path = repo / "student" / "final_models" / "5s_kd_hw08_kw02" / "export_summary.json"

    with open(normalizer_path, "r", encoding="utf-8") as f:
        normalizer = json.load(f)
    with open(export_summary_path, "r", encoding="utf-8") as f:
        export_summary = json.load(f)

    q = export_summary["int8_input_details"]["quantization"]
    input_scale = float(q[0])
    input_zero_point = int(q[1])

    cfg = v1.Config()
    logmel = v1.extract_logmel(str(audio), cfg).astype(np.float32)
    normalized = ((logmel - float(normalizer["mean"])) / float(normalizer["std"])).astype(np.float32)
    q_input = np.round(normalized / input_scale + input_zero_point)
    q_input = np.clip(q_input, -128, 127).astype(np.int8)

    np.save(out_dir / "reference_logmel.npy", logmel)
    np.save(out_dir / "reference_normalized.npy", normalized)
    np.save(out_dir / "reference_input_int8.npy", q_input)

    header = f"""#ifndef BIRDHOUSE_REFERENCE_INPUT_INT8_H_
#define BIRDHOUSE_REFERENCE_INPUT_INT8_H_

#include <cstdint>

#include "firmware/preprocess/preprocess_constants.h"

namespace birdhouse {{

// Reference input generated by Python preprocessing.
// Source audio:
//   {audio}
const int8_t kReferenceInputInt8[kFeatureElements] = {{
{format_int8_array(q_input)}
}};

}}  // namespace birdhouse

#endif  // BIRDHOUSE_REFERENCE_INPUT_INT8_H_
"""
    (out_dir / "reference_input_int8.h").write_text(header, encoding="utf-8")

    summary = {
        "audio": str(audio),
        "logmel_shape": list(logmel.shape),
        "normalized_shape": list(normalized.shape),
        "q_input_shape": list(q_input.shape),
        "q_input_flat_layout": "[mel][frame]",
        "normalizer": normalizer,
        "input_scale": input_scale,
        "input_zero_point": input_zero_point,
        "logmel_min": float(np.min(logmel)),
        "logmel_max": float(np.max(logmel)),
        "normalized_min": float(np.min(normalized)),
        "normalized_max": float(np.max(normalized)),
        "q_input_min": int(np.min(q_input)),
        "q_input_max": int(np.max(q_input)),
    }
    (out_dir / "reference_preprocess_summary.json").write_text(
        json.dumps(summary, indent=2), encoding="utf-8"
    )

    print("Generated reference preprocessing files:")
    print(f"  {out_dir / 'reference_logmel.npy'}")
    print(f"  {out_dir / 'reference_normalized.npy'}")
    print(f"  {out_dir / 'reference_input_int8.npy'}")
    print(f"  {out_dir / 'reference_input_int8.h'}")
    print(f"  {out_dir / 'reference_preprocess_summary.json'}")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()

